spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///tmp/aaa/bbb{label},file:///tmp/aaa/bbb{application},file:///tmp/aaa/bbb{profiles}
server:
  port: 9988
